### ISSUE TITLE
[Feat] Support custom HTTPS port and HTTP port

### ISSUE THREAD

**Issue by PasserDreamer** [gt732/FortiGPT#1]
Although it is possible to connect via IP:{custom port}, an error "IP:{custom port}:22" will appear when clicking on the debug button.

**Comment by gt732** [comment]
Hey, I added custom http/https port and custom ssh port. Just download the new image from dockerhub and follow the new instructions. Let me know if it works out for you!

Thanks!

**Comment by PasserDreamer** [comment]
It works fine, great job!
